"""Added product_description

Revision ID: 5ad6940b7854
Revises: 78c9022c0355
Create Date: 2025-02-16 15:21:14.923559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad6940b7854'
down_revision: Union[str, None] = '78c9022c0355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'product_description')
    # ### end Alembic commands ###
