"""add currency field

Revision ID: cdaed2cefea6
Revises: a101c86fa4d5
Create Date: 2025-06-04 18:27:04.396930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.schemas import PriceCurrencyEnum


# revision identifiers, used by Alembic.
revision: str = 'cdaed2cefea6'
down_revision: Union[str, None] = 'a101c86fa4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


price_currency_enum = sa.Enum(PriceCurrencyEnum, name='price_currency')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    price_currency_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('productbases', sa.Column('currency', price_currency_enum, nullable=True))

    op.execute("UPDATE productbases SET currency = 'uah'")
    op.alter_column('productbases', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productbases', 'currency')
    price_currency_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
